# Generated by Django 4.1.5 on 2023-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=36, unique=True)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("newsletter", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6
                    ),
                ),
                ("tax_rate", models.SmallIntegerField(default=0)),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6
                    ),
                ),
                ("txn", models.CharField(blank=True, max_length=255)),
                ("txn_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
