- name: django migrate
  shell: 'sudo -H -u {{ app_user }} bash -c "source {{install_path}}/app.env && {{app_venv_path}}/bin/python ./manage.py collectstatic --noinput; {{app_venv_path}}/bin/python ./manage.py migrate --noinput;"'
  args:
    chdir: '{{ install_path }}/{{ django_root }}'

- name: reload nginx
  shell: service nginx reload

- name: reload app
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  with_items:
    - "{{ app_name }}_celery"
    - "{{ app_name }}_gunicorn"
