- name: django migrate
  shell: "{{install_path}}/update_django.sh"


- name: reload nginx
  shell: service nginx reload

- name: reload app
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  with_items:
    - "{{ app_name }}_celery"
    - "{{ app_name }}_gunicorn"
